image: python:3.9

pipelines:
  branches:
    master:
      - step:
          name: "Run tests"
          caches:
            - pip
          script:
            - pip install poetry
            - poetry install
            - poetry run pytest
